### ISSUE TITLE
Incorrect position of nested components/views

### ISSUE THREAD

**Issue by Kosiarznerek** [dereksweet/react-native-sliding-panes#4]
It seems like your project has some difficulties with positioning nested components. In my code after several clicks, content automatically sets wrong. However, there is no problem when we've got each component separately.

Please take a look at "Title" at first pane.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35147762/42129267-7b3a555a-7cc0-11e8-880c-41e05d60fe26.gif)

None working code
```javascript
<SlidingPaneWrapper style={{}} ref={(ref: any) => this.panesWrapper = ref}>
   <SlidingPane style={[]} ref={(ref: any) => this.panes[0] = ref}>
      <View>
         <Text style={styles.paneHeaderText}>Title</Text>
      </View>
   </SlidingPane>
/* ... other panels */
</SlidingPaneWrapper>
```

But, all I need to make i work is put Text component outside view

**Comment by Kosiarznerek** [comment]
Actually, it turned out that I've been using wrong react-native version. I've been using Expo SDK v28.0.0 which is based on React Native 0.55.4 and all I had to do was downgrade my SDK to version v26.0.0 which is based on React Native 0.54, “February 2018”.

**Comment by dereksweet** [comment]
Good to know this issue exists in 0.55.4! Thanks for pointing it out, I will add a RN version limitation to the README and take a look at it running on 0.55.4 sometime soon.
